version: '2.1'
services:
  api:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/static
      - /usr/src/app/files
    env_file:
      - django.env
    command: /usr/local/bin/gunicorn wsgi:application -w 2 -b :8000 -t 120 --reload

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/src/front
    volumes_from:
      - api:ro

  postgres:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - django.env
